title: This is main page
h1: Ви на веб-сторінці AlaMix
content:
  news:
    category: новини
    date: 30/X
    title: Заголовок першої новини
    text: Текст новини. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sagittis venenatis sollicitudin.
  media:
    category: медіа
    date: 1/XI
    title: Заголовок другої новини
    text: Текст новини. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sagittis venenatis sollicitudin.
    icons: [news, contacts, portfolio]
  portfolio:
    category: портфоліо
    date: 1/XI
    title: Заголовок третьої новини
    text: Текст новини. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sagittis venenatis sollicitudin.
    icons: [contacts, media, news]